# this uses the Alpine image to run the tests on
# to access the docker container you can use: docker run -it --rm -v ${PWD}:/home jeromeerasmus/docker-alpine-php-composer /bin/sh
# or 
# docker run -it --rm jeromeerasmus/docker-alpine-php /bin/bash

pipelines:
  default:
    - step:
        # this uses the Alpine image to run the tests on
        # to access the docker container you can use: docker run -it --rm -v ${PWD}:/home jeromeerasmus/docker-alpine-php-composer /bin/sh
        image: jeromeerasmus/docker-alpine-php-composer:7.0
        services:
          - docker
        script: 

          # install composer
          - composer install
          - echo $BITBUCKET_CLONE_DIR
         
          # 5. Run the containers
          - docker-compose -f docker-compose.yml run --rm specs  --config=conf.selenium-docker.yml