default:
    paths:
        features: '../../features/single'
        bootstrap:  '../../features/bootstrap'
    context:
        parameters:
            browserstack:
                server: "hub-cloud.browserstack.com"
                capabilities:
                    project: "test-project"
                    build: "behat-browserstack"
                    name: "single_test"

                environments:
                    -
                        browser: "chrome"
